### PR TITLE
Add jhipster logo 

### PR DESCRIPTION
**Pull request by atomfrede**
Official logo of the [jhipster](http://jhipster.github.io/) project.

### CODE REVIEW

**Comment by williamboman** [comment]
I've removed your merge commits and properly rebased on `master` in my repo. You can;
```sh
$ git fetch git@github.com:williamboman/logos.git pr/27 && git reset --hard FETCH_HEAD
```

then `$ git push -f` to update this PR.

**Comment by gilbarbara** [comment]
Sorry guys, I'm not accepting PRs for new logos as stated in the README.

**Comment by atomfrede** [comment]
Sorry I've seen it after the PR was created.

**Comment by gilbarbara** [comment]
No problem at all.
I have downloaded the logo already and I will upload soon!
Thanks

**Comment by gilbarbara** [comment]
Thanks!
Added e893320c80000b2bd5f3cc4c9c02865d88d9675f

**Pull request closed without merging**
