### PR TITLE
Fix V8 logo and add V8 Ignition + TurboFan logos

### PR DESCRIPTION
**Pull request by mathiasbynens**
I’m not sure where you got this logo, but it’s not the official V8 logo. Here’s the correct version.

I’ve also added the V8 Ignition + V8 TurboFan logos. Feel free to cherry-pick and not merge those if you prefer to compress them manually.

The (correct) logos are here: https://github.com/alrra/browser-logos/blob/master/src/README.md#v8 (The SVGs are already compressed, which is why I added them to this PR.)

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hey,

I don't accept PRs.

Btw, I got the logo from the source, probably V8 google repo a few years ago.
What's the difference? I couldn't spot it.

**Comment by mathiasbynens** [comment]
> What's the difference?

There are several differences. The most obvious one is the size of the holes in the `8`:



What would it take for you to fix the existing logo and to add the two additional ones?

**Comment by gilbarbara** [comment]
I can update the V8 logo, no problem.
However, the SVG file you linked is not perfect and has some glitches when compared to the png. Is there another version?

SVG vs PNG
svg-vs-png

**Comment by gilbarbara** [comment]
Nevermind! I was able to export it and that fixed.

**Comment by mathiasbynens** [comment]
You can preview the SVG right here in the GitHub UI (per the screenshot I posted): https://github.com/mathiasbynens/logos/blob/54ab227af5f2bd5098d7499d1106e40c1588ff94/logos/v8.svg

Why do you need to “export” the SVG again? Please ensure that the file you add to this repo matches our official V8 logo.

**Comment by gilbarbara** [comment]
As stated in the README: "All the logos are optimized (removed duplicated paths / excessive grouping / empty defs, linting, etc)."

**Comment by gilbarbara** [comment]
updated in b8a6cbd29fe4aa8a4b28aade6ac861c83907fd4a
I've added the other two logos to my backlog and will upload soon.

Thanks

**Comment by gilbarbara** [comment]
added the other 2 logos in fb68d7874be066ed9c995041eb7450a53727e568

[s]

**Comment by mathiasbynens** [comment]
> As stated in the README: "All the logos are optimized (removed duplicated paths / excessive grouping / empty defs, linting, etc)."

I know, but this has already been done for the SVGs in this PR. So why would you have to do it again?

**Comment by mathiasbynens** [comment]
Anyway thanks for fixing and adding the logos!

**Comment by mathiasbynens** [comment]
The `v8.svg` file you added is 4.02 KB. The official one in my PR is 3.23 KB. Why?

**Comment by gilbarbara** [comment]
@mathiasbynens 
Because the file you linked didn't open correctly in Sketch, probably because the way it was exported or compressed...

This collection isn't about filesize or compression but instead, I try to make it a reliable source of logos that would work on graphics apps, the web and whatever people try to use. For me, SVGs should be portable and work everywhere.

And that are already tons of tools to compress them in the development pipeline so it's better to use a clean source to get the best results.

I don't change the paths when I export the files, so it's the same logo.

[s]

**Pull request closed without merging**
