### PR TITLE
Update Cachet logo to fix thick circle

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by gilbarbara** [comment]
hey!

You should convert the stroke to path in order to avoid this variable thickness.
A stroke of 12px will always have the same width independently of the viewport size.

I will convert it and upload again in the next commit.

[s]

**Comment by jbrooksuk** [comment]
Oh, cool, I didn't know this. Thanks!

**Comment by gilbarbara** [comment]
fixed 17d52cd909f698fd1f55c35cdccefc3224202269

Thanks!

**Comment by jbrooksuk** [comment]
:)

**Pull request closed without merging**
