### PR TITLE
Added Craft CMS, Go Gopher, Precursor logos.

### PR DESCRIPTION
**Pull request by lukeholder**
Popular content management system.

### CODE REVIEW

**Comment by lukeholder** [comment]
Hi there, is there anything I need to fix up to get this merged?

**Comment by lukeholder** [comment]
This fixed #18

**Comment by lukeholder** [comment]
Fixes #30

**Comment by gilbarbara** [comment]
Added Gopher in a6df8c5feb81efde698dc5f200c707c1527dd442
Thanks.

**Pull request closed without merging**
