### PR TITLE
add Pagekit logo (a new Open Source CMS)

### PR DESCRIPTION
**Pull request by saschadube**
Pagekit is a new modern Open Source CMS (https://pagekit.com/) and it would be great to get it included.

Thanks for consideration!

### CODE REVIEW

**Comment by gilbarbara** [comment]
Hello! Thanks for your contribution but I don't accept PRs as stated in the README.
The `master` branch is updated from another branch and everything else is generated from this flow.
I'll add this in the next update! 👍🏻

**Comment by saschadube** [comment]
Sorry, l missed it. Thanks for adding it 😃

**Comment by gilbarbara** [comment]
No problem, keep them coming! :)

**Comment by gilbarbara** [comment]
Added in f4f0886337425dc331172c8b94e5f4e1af2f6e3e
Thanks

**Pull request closed without merging**
